[project]
name = "ycc365"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "graphviz>=0.21",
    "opencv-python>=4.13.0.92",
    "plyer>=2.1.0",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "ultralytics>=8.4.75",
]
